server:
  port: 8081
spring:
  application:
    name: email
  mail:
    host: smtp.gmail.com
    port: 587
    email: # Nhập email đã kích hoạt 2FA
    password: # Thay bằng password đc tạo ra từ app password của Google
    isSSL: false
  protocal: smtp


