server:
  port: 8081
spring:
  application:
    name: email
  mail:
    host: smtp.gmail.com
    port: 587
    email: ## Nhập email
    password: ## Thay bằng password từ password app từ google
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
